ZEC-28 Implement POST, PUT, and DELETE endpoints for products
AnnaMauhay/Zalando-E-Commerce pull request #10
Opened 2024-01-15 11:47 UTC by AnnaMauhay

ZEC-28 Implement POST, PUT, and DELETE endpoints for products

> https://mauhayannaliza.atlassian.net/browse/ZEC-28?atlOrigin=eyJpIjoiZTI0MzJkYWRhYTdjNGQ4MTlkYWRkNTZhMTUyNDE3MzMiLCJwIjoiaiJ9

1.a.  Create new product
> ![Screenshot 2024-01-15 at 12 36 23 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/05c3de5c-e492-47f3-8d70-394670f71d59)

1.b. Fail to add existing product
> ![Screenshot 2024-01-15 at 12 38 26 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/a7ff1d4e-a837-4449-9d3f-7a6f9bcb2d44)

2.a. Edit Existing Product
> ![Screenshot 2024-01-15 at 12 39 36 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/eaf50cee-2bc6-4c18-9fba-b52b3935cd82)

2.b. Fail to edit archived or product that is not created by the seller
> ![Screenshot 2024-01-15 at 12 41 24 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/18b8f328-0304-4673-9bf3-e5e06c703154)

3.a. Archive existing/active product
> ![Screenshot 2024-01-15 at 12 43 47 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/5073863f-a840-4244-b899-ecc28927c40e)

3.b. Fail to archive a non-active/ non existing product
> ![Screenshot 2024-01-15 at 12 44 57 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/fa3ba2b5-e849-4a49-a0c2-ffb60a84c914)

2024-01-15 16:25 UTC, MenilV requested changes
A few changes to responses.

2024-01-15 16:25 UTC, MenilV commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
>              return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
It's good to have a JSON response here

2024-01-15 16:25 UTC, MenilV commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
> +            return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body(e.getMessage());
JSON

2024-01-15 16:25 UTC, MenilV commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
> +        return ResponseEntity.ok(product);
JSON

2024-01-15 16:25 UTC, MenilV commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
> +            return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body(e.getMessage());
JSON

2024-01-15 17:35 UTC, AnnaMauhay commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
> +            return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body(e.getMessage());
![Screenshot 2024-01-15 at 6 35 21 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/1c480505-cb46-4765-a6e3-f23786649736)

2024-01-15 17:35 UTC, AnnaMauhay commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
> +        return ResponseEntity.ok(product);
![Screenshot 2024-01-15 at 6 34 32 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/ab38c4a0-2332-4e63-948f-aaa6f96ed025)

2024-01-15 17:35 UTC, AnnaMauhay commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
> +            return ResponseEntity.status(HttpStatus.NOT_ACCEPTABLE).body(e.getMessage());
![Screenshot 2024-01-15 at 6 33 32 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/eee1570e-6606-4e6b-9b9c-15525bc35d3a)

2024-01-15 17:35 UTC, AnnaMauhay commented on src/main/java/com/zalando/ecommerce/controller/ProductController.java
>              return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
Tested
![Screenshot 2024-01-15 at 6 32 21 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/4e82305f-92f9-4610-a345-7dfae2f82d8c)

2024-01-16 08:38 UTC, faruka-startsteps approved these changes

2024-01-16 08:58 UTC, merged