ZEC-27 Secure product management endpoints with Spring Security, ensuring only admins can access them.
AnnaMauhay/Zalando-E-Commerce pull request #11
Opened 2024-01-15 14:59 UTC by AnnaMauhay

ZEC-27 Secure product management endpoints with Spring Security, ensuring only admins can access them.

> https://mauhayannaliza.atlassian.net/browse/ZEC-27?atlOrigin=eyJpIjoiYzFmMmRkNzlmMjhhNDA3MGJmZmU0ODYwODM0YTNkM2UiLCJwIjoiaiJ9

Adding new product can be accessed by users with SELLER role
![Screenshot 2024-01-15 at 3 52 30 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/c6d8e514-3f9d-483b-9308-d8833eeec274)

but cannot be accessed by users with CUSTOMER role
![Screenshot 2024-01-15 at 3 53 52 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/ebb46485-f194-4bc5-a666-1801ec3ed3b0)

Deleting a product can be accessed by a user with SELLER role
![Screenshot 2024-01-15 at 3 56 19 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/da15972e-b5d6-438d-a484-e35a1cde348a)

but cannot be accessed by a user with CUSTOMER role
![Screenshot 2024-01-15 at 3 54 59 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/c14293c1-1c57-4a2d-9fab-927b47079424)

Same with editing product details:
![Screenshot 2024-01-15 at 3 58 09 PM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/e9412471-3d1b-4144-99af-b0c6e8e95ca4)

2024-01-15 16:23 UTC, MenilV requested changes
One minor thing to change

2024-01-15 16:23 UTC, MenilV commented on src/main/java/com/zalando/ecommerce/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.FORBIDDEN).body(message);
let's send JSON responses instead of string

2024-01-16 09:23 UTC, AnnaMauhay commented on src/main/java/com/zalando/ecommerce/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.FORBIDDEN).body(message);
Done 👍 
![Screenshot 2024-01-16 at 10 22 51 AM](https://github.com/AnnaMauhay/Zalando-E-Commerce/assets/5255871/c502035b-46e5-4cc7-8c4d-5c889d3a6339)

2024-01-16 09:48 UTC, faruka-startsteps approved these changes

2024-01-16 09:53 UTC, merged