ZEC-69 Create integration test on Product controller.
AnnaMauhay/Zalando-E-Commerce pull request #20
Opened 2024-02-05 08:09 UTC by AnnaMauhay

- Implement H2 db for the test.
- Endpoints that require JWT were not covered yet.

https://mauhayannaliza.atlassian.net/browse/ZEC-69?atlOrigin=eyJpIjoiMDhiZDkzYTZlYWVmNGRkMWIyYmRjNzgxNzE0MWY3NzMiLCJwIjoiaiJ9

2024-02-05 09:57 UTC, faruka-startsteps requested changes

2024-02-05 09:57 UTC, faruka-startsteps commented on src/test/java/com/zalando/ecommerce/controller/ProductControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
use `@WebMvcTest`

2024-02-06 10:24 UTC, AnnaMauhay commented on src/test/java/com/zalando/ecommerce/controller/ProductControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
Hello, 
Referring to our earlier discussion, I would proceed with the @SpringBootTest and have modified the code to include mocked users for secured endpoints.

2024-02-06 10:33 UTC, MenilV approved these changes

2024-02-06 10:42 UTC, merged